# Generated by Django 3.2.4 on 2021-06-09 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 10, 1, 24, 2, 476790)),
        ),
    ]
